--
--@Integrantes: 
--      Morales Téllez Carlos Gamaliel
--      Sanchez Díaz María Beatriz
--@Fecha de creación: 12 de junio de 2020
--@Descripción: 
--         DDL BIBLIOTECA



-- 
-- TABLE: AREA 
--

CREATE TABLE AREA(
    AREA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE     VARCHAR2(100)    NOT NULL,
    CONSTRAINT AREA_PK PRIMARY KEY (AREA_ID)
    USING INDEX (     
        CREATE UNIQUE INDEX AREA_PK ON AREA(AREA_ID)
        TABLESPACE INDX_TBS)
) TABLESPACE BIBLIOTECAS_TBS;




-- 
-- TABLE: BIBLIOTECA 
--

CREATE TABLE BIBLIOTECA(
    BIBLIOTECA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    FOLIO_UK         VARCHAR2(5)      NOT NULL,
    LATITUD          NUMBER(8, 5)     NOT NULL,
    LONGITUD         NUMBER(8, 5)     NOT NULL,
    WEB              VARCHAR2(100)    NOT NULL,
    DIRECCION        VARCHAR2(500)    NOT NULL,
    CONSTRAINT BIBLIOTECA_PK PRIMARY KEY (BIBLIOTECA_ID)
    USING INDEX (     
        CREATE UNIQUE INDEX BIBLIOTECA_PK ON BIBLIOTECA(BIBLIOTECA_ID)
        TABLESPACE INDX_TBS)
) TABLESPACE BIBLIOTECAS_TBS;



-- 
-- TABLE: AREA_BIBLIOTECA 
--

CREATE TABLE AREA_BIBLIOTECA(
    AREA_BIBLIOTECA_ID    NUMBER(10, 0)    NOT NULL,
    BIBLIOTECA_ID         NUMBER(10, 0)    NOT NULL,
    AREA_ID               NUMBER(10, 0)    NOT NULL,
    CONSTRAINT AREA_BIBLIOTECA_AREA_ID_FK FOREIGN KEY (AREA_ID)
    REFERENCES AREA(AREA_ID),
    CONSTRAINT AREA_BIBLIOTECA_BIBLIOTECA_ID_FK FOREIGN KEY (BIBLIOTECA_ID)
    REFERENCES BIBLIOTECA(BIBLIOTECA_ID),
    CONSTRAINT AREA_BIBLIOTECA_PK PRIMARY KEY (AREA_BIBLIOTECA_ID)
    USING INDEX (     
        CREATE UNIQUE INDEX AREA_BIBLIOTECA_PK ON AREA_BIBLIOTECA(AREA_BIBLIOTECA_ID)
        TABLESPACE INDX_TBS)
) TABLESPACE BIBLIOTECAS_TBS;

-- 
-- TABLE: USUARIO 
--

CREATE TABLE USUARIO(
    USUARIO_ID              NUMBER(10, 0)    NOT NULL,
    NOMBRE                  VARCHAR2(40)     NOT NULL,
    AP_PATERNO              VARCHAR2(40)     NOT NULL,
    AP_MATERNO              VARCHAR2(40)     NOT NULL,
    MATRICULA               VARCHAR2(18)     NOT NULL,
    EMAIL                   VARCHAR2(100)    NOT NULL,
    SEMESTRE                NUMBER(2, 0),
    USERNAME                VARCHAR2(40)     NOT NULL,
    PASSWORD                VARCHAR2(40)     NOT NULL,
    CON_PRESTAMO            NUMBER(1, 0)     NOT NULL,
    CON_PRESTAMO_VENCIDO    NUMBER(1, 0)     NOT NULL,
    FOTO                    BLOB             NOT NULL,
    CONSTRAINT USUARIO_PK PRIMARY KEY (USUARIO_ID)
    USING INDEX (     
        CREATE UNIQUE INDEX USUARIO_PK ON USUARIO(USUARIO_ID)
        TABLESPACE INDX_TBS)
) TABLESPACE BIBLIOTECAS_TBS
  LOB (FOTO) STORE AS SECUREFILE (TABLESPACE LOBS_TBS);



CREATE TABLE PRESTAMO(
    PRESTAMO_ID       NUMBER(10, 0)    NOT NULL,
    USUARIO_ID        NUMBER(10, 0)    NOT NULL,
    FECHA_PRESTAMO    DATE             NOT NULL,
    FECHA_ENTREGA     DATE,
    VIGENCIA          DATE             NOT NULL,
    IMPORTE_MULTA     NUMBER(6, 2),
    CONSTRAINT PRESTAMO_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT PRESTAMO_PK PRIMARY KEY (PRESTAMO_ID, USUARIO_ID)
    USING INDEX (     
        CREATE UNIQUE INDEX PRESTAMO_PK ON PRESTAMO(PRESTAMO_ID)
        TABLESPACE INDX_TBS)
) TABLESPACE BIBLIOTECAS_TBS;

--
-- ORORGANDO ACCESO A TODAS LAS TABLAS A MOSAPROY_RECURSOS
--

grant select, insert, update, delete on mosaproy_bibliotecas.area, mosproy_bibliotecas.biblioteca,
  mosaproy_bibliotecas.area_biblioteca, mosaproy_bibliotecas.usuario, mosaproy_bibliotecas.prestamo 
  to mosaproy_recursos;
