insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (251, 'Inj oth blood vessels at forearm level, right arm, sequela', to_date('24/03/2018','dd/mm/yyyy'), 38, 61);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (252, 'Drug/chem diab with prolif diab rtnop with trctn dtch macula', to_date('24/03/2018','dd/mm/yyyy'), 364, 798);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (253, 'Toxic effect of venom of black widow spider, assault', to_date('24/03/2018','dd/mm/yyyy'), 288, 393);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (254, 'Conjunctival cysts, unspecified eye', to_date('24/03/2018','dd/mm/yyyy'), 139, 675);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (255, 'Nondisp fx of medial phalanx of right lesser toe(s), sequela', to_date('24/03/2018','dd/mm/yyyy'), 244, 540);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (256, 'Unsp fx low end unsp ulna, 7thJ', to_date('24/03/2018','dd/mm/yyyy'), 39, 772);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (257, 'Calculus of gallbladder with other cholecystitis', to_date('24/03/2018','dd/mm/yyyy'), 171, 369);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (258, 'Other retinoschisis and retinal cysts, right eye', to_date('24/03/2018','dd/mm/yyyy'), 212, 380);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (259, 'Other superficial bite of left wrist, initial encounter', to_date('24/03/2018','dd/mm/yyyy'), 67, 148);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (260, 'Pneumatic hammer syndrome, sequela', to_date('24/03/2018','dd/mm/yyyy'), 303, 184);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (261, 'Insect bite (nonvenomous) of right forearm, init encntr', to_date('24/03/2018','dd/mm/yyyy'), 342, 401);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (262, 'Toxic effect of fiberglass, intentional self-harm, init', to_date('24/03/2018','dd/mm/yyyy'), 332, 353);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (263, 'Minor laceration of unsp external jugular vein, init encntr', to_date('24/03/2018','dd/mm/yyyy'), 58, 892);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (264, 'Dislocation of oth parts of lumbar spine and pelvis, sequela', to_date('24/03/2018','dd/mm/yyyy'), 236, 117);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (265, 'Carbuncle of left upper limb', to_date('24/03/2018','dd/mm/yyyy'), 196, 504);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (266, 'Crystalline deposits in vitreous body, left eye', to_date('24/03/2018','dd/mm/yyyy'), 114, 398);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (267, 'Complete traum amp of right shldr/up arm, level unsp, init', to_date('24/03/2018','dd/mm/yyyy'), 84, 61);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (268, 'Concussion and edema of cervical spinal cord', to_date('24/03/2018','dd/mm/yyyy'), 118, 527);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (269, 'Inj flexor musc/fasc/tend l rng fngr at forearm level, init', to_date('24/03/2018','dd/mm/yyyy'), 214, 584);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (270, 'Displacement of implanted urinary sphincter', to_date('24/03/2018','dd/mm/yyyy'), 292, 65);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (271, 'Oth fx upr & low end unsp fibula, 7thH', to_date('24/03/2018','dd/mm/yyyy'), 261, 531);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (272, 'Unsp fracture of upper end of right humerus, init for opn fx', to_date('24/03/2018','dd/mm/yyyy'), 285, 546);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (273, 'Toxic effect of alcohols, accidental (unintentional), subs', to_date('24/03/2018','dd/mm/yyyy'), 101, 665);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (274, 'Oth fracture of r low leg, subs for clos fx w routn heal', to_date('24/03/2018','dd/mm/yyyy'), 368, 337);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (275, 'Exposure to melting of plastic jewelry, subsequent encounter', to_date('24/03/2018','dd/mm/yyyy'), 184, 840);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (276, 'Nondisp fx of lateral condyle of r tibia, 7thF', to_date('24/03/2018','dd/mm/yyyy'), 335, 471);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (277, 'Dislocation of interphalangeal joint of unsp great toe', to_date('24/03/2018','dd/mm/yyyy'), 220, 241);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (278, 'Stress fracture, ankle, foot and toes', to_date('24/03/2018','dd/mm/yyyy'), 44, 838);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (279, 'Breakdown (mechanical) of cardiac electronic device', to_date('24/03/2018','dd/mm/yyyy'), 210, 743);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (280, 'Unsp car occupant injured in clsn w pedl cyc nontraf, init', to_date('24/03/2018','dd/mm/yyyy'), 85, 379);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (281, 'Superficial frostbite of left foot, subsequent encounter', to_date('24/03/2018','dd/mm/yyyy'), 356, 245);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (282, 'Nondisp transverse fx shaft of l femr, 7thK', to_date('24/03/2018','dd/mm/yyyy'), 167, 433);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (283, 'Chronic angle-closure glaucoma, right eye, mild stage', to_date('24/03/2018','dd/mm/yyyy'), 59, 698);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (284, 'Prolonged stay in weightless environment, initial encounter', to_date('24/03/2018','dd/mm/yyyy'), 170, 380);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (285, 'Blister (nonthermal) of penis, subsequent encounter', to_date('24/03/2018','dd/mm/yyyy'), 180, 816);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (286, 'Insect bite (nonvenomous) of right hand, sequela', to_date('24/03/2018','dd/mm/yyyy'), 361, 708);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (287, 'Toxic effect of contact with venomous frog, assault, sequela', to_date('24/03/2018','dd/mm/yyyy'), 93, 433);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (288, 'Oth fx shaft of l fibula, 7thQ', to_date('24/03/2018','dd/mm/yyyy'), 32, 734);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (289, 'Unsp inj flexor musc/fasc/tend unsp fngr at forarm lv, sqla', to_date('24/03/2018','dd/mm/yyyy'), 323, 3);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (290, 'Exposure to ignition or melting of nightwear, init encntr', to_date('24/03/2018','dd/mm/yyyy'), 333, 276);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (291, 'Unsp trochan fx r femr, 7thF', to_date('24/03/2018','dd/mm/yyyy'), 3, 576);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (292, 'Bariatric surgery status complicating childbirth', to_date('24/03/2018','dd/mm/yyyy'), 218, 45);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (293, 'Legal intervention involving baton, suspect injured, sequela', to_date('24/03/2018','dd/mm/yyyy'), 60, 681);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (294, 'Oth athscl autol vein bypass of the extrm, bilateral legs', to_date('24/03/2018','dd/mm/yyyy'), 53, 538);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (295, 'Other superficial injuries of thumb', to_date('24/03/2018','dd/mm/yyyy'), 253, 614);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (296, 'Cerebral ischemia', to_date('24/03/2018','dd/mm/yyyy'), 312, 285);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (297, 'Underdosing of caffeine', to_date('24/03/2018','dd/mm/yyyy'), 63, 505);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (298, 'Pasngr in hv veh inj pick-up truck, pk-up/van in traf, init', to_date('24/03/2018','dd/mm/yyyy'), 305, 289);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (299, 'Lateral dislocation of unspecified patella', to_date('24/03/2018','dd/mm/yyyy'), 394, 235);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (300, 'Yatapoxvirus infections', to_date('24/03/2018','dd/mm/yyyy'), 281, 394);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (301, 'Other juvenile arthritis, right wrist', to_date('24/03/2018','dd/mm/yyyy'), 110, 151);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (302, 'Fracture of alveolus of left mandible, sequela', to_date('24/03/2018','dd/mm/yyyy'), 140, 203);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (303, 'Secondary malignant neoplasm of other respiratory organs', to_date('24/03/2018','dd/mm/yyyy'), 64, 881);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (304, 'Lateral subluxation of left patella', to_date('24/03/2018','dd/mm/yyyy'), 363, 342);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (305, 'Unsp fracture of unsp femur, init for opn fx type I/2', to_date('24/03/2018','dd/mm/yyyy'), 255, 619);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (306, 'Disp fx of capitate bone, unsp wrist, subs for fx w nonunion', to_date('24/03/2018','dd/mm/yyyy'), 400, 464);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (307, 'Algoneurodystrophy, hand', to_date('24/03/2018','dd/mm/yyyy'), 207, 814);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (308, 'Inj unsp blood vessel at shoulder and upper arm level', to_date('24/03/2018','dd/mm/yyyy'), 218, 831);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (309, 'Malignant neoplasm of central portion of breast, male', to_date('24/03/2018','dd/mm/yyyy'), 278, 260);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (310, 'CR(E)ST syndrome', to_date('24/03/2018','dd/mm/yyyy'), 34, 499);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (311, 'Maternal care for excessive fetal growth, second trimester', to_date('24/03/2018','dd/mm/yyyy'), 104, 82);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (312, 'Toxic effects of glycols', to_date('24/03/2018','dd/mm/yyyy'), 243, 757);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (313, 'Poisoning by antidiarrheal drugs, accidental, sequela', to_date('24/03/2018','dd/mm/yyyy'), 350, 48);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (314, 'Unilateral inguinal hernia, with obstruction, w/o gangrene', to_date('24/03/2018','dd/mm/yyyy'), 300, 375);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (315, 'Laceration without foreign body of unsp hand, init encntr', to_date('24/03/2018','dd/mm/yyyy'), 291, 703);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (316, 'Toxic effect of contact w Portugese Man-o-war, undet, subs', to_date('24/03/2018','dd/mm/yyyy'), 289, 311);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (317, 'Toxic effect of herbicides and fungicides, self-harm, subs', to_date('24/03/2018','dd/mm/yyyy'), 338, 488);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (318, 'Recurrent dislocation, left knee', to_date('24/03/2018','dd/mm/yyyy'), 40, 346);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (319, 'Disp fx of med malleolus of l tibia, 7thB', to_date('24/03/2018','dd/mm/yyyy'), 232, 519);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (320, 'Disp fx of proximal phalanx of right ring finger, sequela', to_date('24/03/2018','dd/mm/yyyy'), 247, 597);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (321, 'Unspecified chronic otitis externa, left ear', to_date('24/03/2018','dd/mm/yyyy'), 57, 252);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (322, 'Unsp inj flexor musc/fasc/tend l mid fngr at forarm lv, sqla', to_date('24/03/2018','dd/mm/yyyy'), 294, 276);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (323, 'Infect/inflm reaction due to unsp int joint prosth, subs', to_date('24/03/2018','dd/mm/yyyy'), 312, 725);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (324, 'Military operations involving friendly fire', to_date('24/03/2018','dd/mm/yyyy'), 342, 510);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (325, 'Nondisp spiral fx shaft of l fibula, 7thN', to_date('24/03/2018','dd/mm/yyyy'), 330, 820);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (326, 'Atrophic nonflaccid tympanic membrane, bilateral', to_date('24/03/2018','dd/mm/yyyy'), 161, 790);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (327, 'Other reactive arthropathies, hand', to_date('24/03/2018','dd/mm/yyyy'), 60, 859);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (328, 'Fracture of tooth (traumatic), subs for fx w delay heal', to_date('24/03/2018','dd/mm/yyyy'), 137, 8);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (329, 'Strain of other muscles and tendons at lower leg level', to_date('24/03/2018','dd/mm/yyyy'), 184, 873);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (330, 'Prsn brd/alit pedl cyc injured in nonclsn transport accident', to_date('24/03/2018','dd/mm/yyyy'), 290, 430);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (331, 'Long term (current) use of insulin', to_date('24/03/2018','dd/mm/yyyy'), 358, 485);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (332, 'Poisoning by and adverse effect of heroin', to_date('24/03/2018','dd/mm/yyyy'), 202, 577);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (333, 'Complete lesion at C5 level of cervical spinal cord, subs', to_date('24/03/2018','dd/mm/yyyy'), 101, 342);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (334, 'Oth foreign object in resp tract, part unsp cause oth injury', to_date('24/03/2018','dd/mm/yyyy'), 101, 161);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (335, 'Nondisp transcondy fx l humerus, subs for fx w routn heal', to_date('24/03/2018','dd/mm/yyyy'), 272, 536);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (336, 'Nondisp pilon fx l tibia, 7thF', to_date('24/03/2018','dd/mm/yyyy'), 308, 487);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (337, 'Unsp open wound of unsp finger with damage to nail, sequela', to_date('24/03/2018','dd/mm/yyyy'), 345, 32);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (338, 'Oth disord of brst/lactatn assoc w pregnancy and the puerp', to_date('24/03/2018','dd/mm/yyyy'), 291, 888);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (339, 'Anterior displaced Type II dens fracture, sequela', to_date('24/03/2018','dd/mm/yyyy'), 372, 365);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (340, 'Poisoning by smallpox vaccines, intentional self-harm, init', to_date('24/03/2018','dd/mm/yyyy'), 238, 654);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (341, 'Occ of anml-drn veh inj in trnsp acc w miltry vehicle, sqla', to_date('24/03/2018','dd/mm/yyyy'), 190, 316);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (342, 'Athscl nonbiol bypass of the left leg w ulceration of ankle', to_date('24/03/2018','dd/mm/yyyy'), 337, 279);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (343, 'Traum hemor r cereb w LOC >24 hr w/o ret consc w surv, sqla', to_date('24/03/2018','dd/mm/yyyy'), 342, 148);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (344, 'Other abnormal products of conception', to_date('24/03/2018','dd/mm/yyyy'), 67, 46);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (345, 'Superficial fb of unsp external genital organs, female, subs', to_date('24/03/2018','dd/mm/yyyy'), 368, 225);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (346, 'Fx unsp prt of nk of l femr, 7thN', to_date('24/03/2018','dd/mm/yyyy'), 214, 535);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (347, 'Unsp car occupant injured in collision w 2/3-whl mv nontraf', to_date('24/03/2018','dd/mm/yyyy'), 202, 354);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (348, 'Corrosion of second degree of left wrist', to_date('24/03/2018','dd/mm/yyyy'), 106, 682);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (349, 'Obstructive hydrocephalus', to_date('24/03/2018','dd/mm/yyyy'), 66, 665);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (350, 'Avalanche, landslide, or mudslide, initial encounter', to_date('24/03/2018','dd/mm/yyyy'), 25, 98);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (351, 'Other allergic rhinitis', to_date('24/03/2018','dd/mm/yyyy'), 91, 885);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (352, 'Opioid abuse with intoxication, uncomplicated', to_date('24/03/2018','dd/mm/yyyy'), 2, 807);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (353, 'Carcinoma in situ of rectum', to_date('24/03/2018','dd/mm/yyyy'), 69, 586);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (354, 'Unsp inj less saphenous at low leg level, left leg, sequela', to_date('24/03/2018','dd/mm/yyyy'), 93, 790);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (355, 'Poisoning by oth psychodysleptics, undetermined, subs encntr', to_date('24/03/2018','dd/mm/yyyy'), 347, 445);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (356, 'Displaced fracture of intermediate cuneiform of left foot', to_date('24/03/2018','dd/mm/yyyy'), 185, 124);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (357, 'Toxic effect of contact w stingray, accidental, subs', to_date('24/03/2018','dd/mm/yyyy'), 213, 514);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (358, 'Rheumatoid heart disease w rheumatoid arthritis of unsp hand', to_date('24/03/2018','dd/mm/yyyy'), 75, 179);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (359, 'Need for assist at home & no house memb able to render care', to_date('24/03/2018','dd/mm/yyyy'), 342, 389);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (360, 'Burn of unspecified degree of back of left hand, init encntr', to_date('24/03/2018','dd/mm/yyyy'), 54, 87);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (361, 'Oth fx shaft of l ulna, 7thF', to_date('24/03/2018','dd/mm/yyyy'), 275, 676);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (362, 'Subluxation of MTP joint of left great toe, init', to_date('24/03/2018','dd/mm/yyyy'), 358, 127);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (363, 'Contus/lac/hem brainstem w LOC >24 hr w ret consc lev, subs', to_date('24/03/2018','dd/mm/yyyy'), 220, 191);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (364, 'Other bursal cyst, right hip', to_date('24/03/2018','dd/mm/yyyy'), 185, 52);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (365, 'Other stimulant abuse with stimulant-induced mood disorder', to_date('24/03/2018','dd/mm/yyyy'), 98, 480);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (366, 'Other injury of transverse colon, sequela', to_date('24/03/2018','dd/mm/yyyy'), 145, 134);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (367, 'Syndrome of infant of a diabetic mother', to_date('24/03/2018','dd/mm/yyyy'), 26, 822);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (368, 'Acquired absence of left finger(s)', to_date('24/03/2018','dd/mm/yyyy'), 104, 633);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (369, 'Child sexual abuse, confirmed, subsequent encounter', to_date('24/03/2018','dd/mm/yyyy'), 264, 53);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (370, 'Burn due to localized fire on board fishing boat, init', to_date('24/03/2018','dd/mm/yyyy'), 368, 85);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (371, 'Inhalant dependence with inhalant-induced anxiety disorder', to_date('24/03/2018','dd/mm/yyyy'), 213, 427);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (372, 'Legal intervention, means unsp, bystander injured, subs', to_date('24/03/2018','dd/mm/yyyy'), 285, 752);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (373, 'Morbidly adherent placenta', to_date('24/03/2018','dd/mm/yyyy'), 264, 422);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (374, 'Other congenital musculoskeletal deformities', to_date('24/03/2018','dd/mm/yyyy'), 301, 424);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (375, 'Unsp inj flxr musc/fasc/tend r idx fngr at wrs/hnd lv, subs', to_date('24/03/2018','dd/mm/yyyy'), 174, 64);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (376, 'Adverse effect of other fibrinolysis-affecting drugs', to_date('24/03/2018','dd/mm/yyyy'), 180, 181);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (377, 'Age-related osteopor w current path fracture, l forearm', to_date('24/03/2018','dd/mm/yyyy'), 9, 370);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (378, 'Nondisplaced dome fracture of left talus, sequela', to_date('24/03/2018','dd/mm/yyyy'), 359, 180);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (379, 'Osteonecrosis due to previous trauma, right shoulder', to_date('24/03/2018','dd/mm/yyyy'), 396, 317);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (380, 'Unstable burst fracture of T9-T10 vertebra', to_date('24/03/2018','dd/mm/yyyy'), 381, 278);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (381, 'Oth parlyt synd fol oth cerebvasc disease aff left dom side', to_date('24/03/2018','dd/mm/yyyy'), 339, 763);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (382, 'Ischiocapsular ligament sprain of right hip, subs encntr', to_date('24/03/2018','dd/mm/yyyy'), 328, 223);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (383, 'Pnctr w/o fb of unsp extrn genital organs, female, sequela', to_date('24/03/2018','dd/mm/yyyy'), 352, 894);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (384, 'Traum subdr hem w LOC of 30 minutes or less', to_date('24/03/2018','dd/mm/yyyy'), 47, 310);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (385, 'Keratopathy (bullous aphakic) fol cataract surgery, r eye', to_date('24/03/2018','dd/mm/yyyy'), 125, 828);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (386, 'Superior glenoid labrum lesion of left shoulder, subs encntr', to_date('24/03/2018','dd/mm/yyyy'), 279, 463);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (387, 'Sltr-haris Type II physeal fx lower end of right tibia', to_date('24/03/2018','dd/mm/yyyy'), 60, 118);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (388, 'Lesch-Nyhan syndrome', to_date('24/03/2018','dd/mm/yyyy'), 304, 852);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (389, 'Perforated corneal ulcer, right eye', to_date('24/03/2018','dd/mm/yyyy'), 346, 336);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (390, 'Poisn by unsp hormones and synthetic sub, assault, sequela', to_date('24/03/2018','dd/mm/yyyy'), 8, 714);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (391, 'Arthus phenomenon', to_date('24/03/2018','dd/mm/yyyy'), 339, 673);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (392, 'Unsp inj flxr musc/fasc/tend r rng fngr at wrs/hnd lv, sqla', to_date('24/03/2018','dd/mm/yyyy'), 175, 622);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (393, 'Type 2 diabetes mellitus without complications', to_date('24/03/2018','dd/mm/yyyy'), 67, 43);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (394, 'Displ bimalleol fx r low leg, 7thN', to_date('24/03/2018','dd/mm/yyyy'), 313, 439);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (395, 'Puncture wound with foreign body, left foot, init encntr', to_date('24/03/2018','dd/mm/yyyy'), 175, 833);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (396, 'Other and unspecified effects of other external causes', to_date('24/03/2018','dd/mm/yyyy'), 341, 449);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (397, 'Salter-Harris Type III physeal fracture of left  metatarsal', to_date('24/03/2018','dd/mm/yyyy'), 43, 181);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (398, 'Cysticercosis of eye', to_date('24/03/2018','dd/mm/yyyy'), 27, 498);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (399, 'Corrosion of other parts of respiratory tract, sequela', to_date('24/03/2018','dd/mm/yyyy'), 263, 151);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (400, 'Displaced unsp condyle fx lower end of unsp femur, sequela', to_date('24/03/2018','dd/mm/yyyy'), 339, 617);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (401, 'Mycosis fungoides, extranodal and solid organ sites', to_date('24/03/2018','dd/mm/yyyy'), 2, 20);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (402, 'Unspecified fracture of fourth metacarpal bone, left hand', to_date('24/03/2018','dd/mm/yyyy'), 231, 238);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (403, 'Frostbite with tissue necrosis of right arm, subs encntr', to_date('24/03/2018','dd/mm/yyyy'), 230, 752);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (404, 'Malignant neoplasm of overlapping sites of urinary organs', to_date('24/03/2018','dd/mm/yyyy'), 255, 875);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (405, 'Expsr to chng in air pressure in arcrft during ascent, init', to_date('24/03/2018','dd/mm/yyyy'), 230, 897);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (406, 'Legal intervnt w unsp blunt objects, suspect injured, subs', to_date('24/03/2018','dd/mm/yyyy'), 56, 294);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (407, 'Juvenile osteochondrosis of metatarsus, unspecified foot', to_date('24/03/2018','dd/mm/yyyy'), 250, 95);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (408, 'Fx condylar process of mandible, unspecified side, 7thB', to_date('24/03/2018','dd/mm/yyyy'), 327, 570);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (409, 'Displ oblique fx shaft of unsp tibia, 7thF', to_date('24/03/2018','dd/mm/yyyy'), 294, 456);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (410, 'Idiopathic aseptic necrosis of unspecified ankle', to_date('24/03/2018','dd/mm/yyyy'), 40, 209);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (411, 'Milt op w explosn of improv explosv device, milt, subs', to_date('24/03/2018','dd/mm/yyyy'), 62, 266);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (412, 'Laceration of unsp part of small intestine, init encntr', to_date('24/03/2018','dd/mm/yyyy'), 264, 601);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (413, 'Fetal anemia and thrombocytopenia, first trimester, fetus 3', to_date('24/03/2018','dd/mm/yyyy'), 18, 545);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (414, 'Traumatic rupture of lumbar intervertebral disc, sequela', to_date('24/03/2018','dd/mm/yyyy'), 83, 380);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (415, 'Laceration of other part of small intestine', to_date('24/03/2018','dd/mm/yyyy'), 2, 232);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (416, 'Poisoning by antiallerg/antiemetic, accidental, sequela', to_date('24/03/2018','dd/mm/yyyy'), 216, 111);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (417, 'Miotic pupillary cyst', to_date('24/03/2018','dd/mm/yyyy'), 260, 9);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (418, 'Nondisp fx of nk of 4th MC bone, l hand, 7thD', to_date('24/03/2018','dd/mm/yyyy'), 217, 54);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (419, 'Breakdown of prosth dev/implnt/grft of genitl trct', to_date('24/03/2018','dd/mm/yyyy'), 175, 888);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (420, 'Strain intrns musc/fasc/tend r idx fngr at wrs/hnd lv, sqla', to_date('24/03/2018','dd/mm/yyyy'), 195, 479);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (421, 'Puncture wound without foreign body of right buttock', to_date('24/03/2018','dd/mm/yyyy'), 336, 833);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (422, 'Encntr screen for infections w sexl mode of transmiss', to_date('24/03/2018','dd/mm/yyyy'), 57, 226);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (423, 'Pnctr w fb of unsp great toe w/o damage to nail, init', to_date('24/03/2018','dd/mm/yyyy'), 25, 815);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (424, 'Intestinal adhesions w obst (postprocedural) (postinfection)', to_date('24/03/2018','dd/mm/yyyy'), 400, 541);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (425, 'Displaced spiral fracture of shaft of left fibula, sequela', to_date('24/03/2018','dd/mm/yyyy'), 9, 337);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (426, 'Unspecified sprain of left thumb, initial encounter', to_date('24/03/2018','dd/mm/yyyy'), 91, 28);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (427, 'Rupture of synovium, right wrist', to_date('24/03/2018','dd/mm/yyyy'), 345, 769);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (428, 'Sprain of right sternoclavicular joint, sequela', to_date('24/03/2018','dd/mm/yyyy'), 222, 101);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (429, 'Contusion of left little finger with damage to nail, sequela', to_date('24/03/2018','dd/mm/yyyy'), 379, 656);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (430, 'Neoplasm of unsp behavior of other genitourinary organs', to_date('24/03/2018','dd/mm/yyyy'), 178, 190);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (431, 'Malignant neoplasm of unsp part of right adrenal gland', to_date('24/03/2018','dd/mm/yyyy'), 104, 866);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (432, 'Underdosing of amphetamines, sequela', to_date('24/03/2018','dd/mm/yyyy'), 81, 44);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (433, 'Other displaced dens fracture, sequela', to_date('24/03/2018','dd/mm/yyyy'), 274, 507);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (434, 'Displaced comminuted fracture of shaft of left femur, init', to_date('24/03/2018','dd/mm/yyyy'), 275, 71);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (435, 'Unspecified injury of deep palmar arch of right hand', to_date('24/03/2018','dd/mm/yyyy'), 264, 741);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (436, 'Contact with other rodent', to_date('24/03/2018','dd/mm/yyyy'), 5, 337);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (437, 'Crushing injury of other specified parts of neck, sequela', to_date('24/03/2018','dd/mm/yyyy'), 382, 27);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (438, 'Unsp intracranial injury w LOC of 30 minutes or less', to_date('24/03/2018','dd/mm/yyyy'), 55, 729);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (439, 'Oth fx shaft of l ulna, subs for opn fx type I/2 w nonunion', to_date('24/03/2018','dd/mm/yyyy'), 277, 49);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (440, 'Corrosion of third degree of forehead and cheek', to_date('24/03/2018','dd/mm/yyyy'), 323, 505);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (441, 'Other premature separation of placenta, second trimester', to_date('24/03/2018','dd/mm/yyyy'), 308, 494);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (442, 'Strain of flexor musc/fasc/tend finger at wrs/hnd lv, subs', to_date('24/03/2018','dd/mm/yyyy'), 304, 105);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (443, 'Oth dis of bld/bld-form org/immun mechnsm comp preg, 1st tri', to_date('24/03/2018','dd/mm/yyyy'), 261, 897);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (444, 'Burn of 3rd deg mu sites of unsp lower limb, except ank/ft', to_date('24/03/2018','dd/mm/yyyy'), 158, 746);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (445, 'Major lacerat great saph at hip and thi lev, unsp leg, init', to_date('24/03/2018','dd/mm/yyyy'), 214, 511);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (446, 'Central retinal artery occlusion', to_date('24/03/2018','dd/mm/yyyy'), 289, 256);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (447, 'Inj extensor musc/fasc/tend left little finger at wrs/hnd lv', to_date('24/03/2018','dd/mm/yyyy'), 238, 518);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (448, 'Oth foreign object in bronchus causing oth injury, subs', to_date('24/03/2018','dd/mm/yyyy'), 68, 504);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (449, 'Other sprain of unspecified thumb, subsequent encounter', to_date('24/03/2018','dd/mm/yyyy'), 99, 890);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (450, 'Nondisp longitud fx unsp patella, 7thM', to_date('24/03/2018','dd/mm/yyyy'), 313, 314);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (451, 'Oth aplastic anemias and other bone marrow failure syndromes', to_date('24/03/2018','dd/mm/yyyy'), 254, 784);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (452, 'Burn of third degree of left knee', to_date('24/03/2018','dd/mm/yyyy'), 322, 600);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (453, 'Nodular scler Hodgkin lymph, nodes of axilla and upper limb', to_date('24/03/2018','dd/mm/yyyy'), 236, 281);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (454, 'Postproc seroma of left eye and adnexa fol an opth procedure', to_date('24/03/2018','dd/mm/yyyy'), 41, 207);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (455, 'Poisoning by inhaled anesthetics, assault, subs encntr', to_date('24/03/2018','dd/mm/yyyy'), 290, 811);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (456, 'Legal intervnt involving oth means, bystander injured, init', to_date('24/03/2018','dd/mm/yyyy'), 146, 222);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (457, 'Cntct w nonvenom plant thorns & spines & sharp leaves, subs', to_date('24/03/2018','dd/mm/yyyy'), 222, 524);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (458, 'Chronic dacryocystitis', to_date('24/03/2018','dd/mm/yyyy'), 40, 769);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (459, 'Nondisp transverse fx shaft of r fibula, 7thB', to_date('24/03/2018','dd/mm/yyyy'), 259, 502);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (460, 'Nondisp fx of dist phalanx of l great toe, init for opn fx', to_date('24/03/2018','dd/mm/yyyy'), 83, 880);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (461, 'Unsp fracture of unsp calcaneus, subs for fx w malunion', to_date('24/03/2018','dd/mm/yyyy'), 369, 66);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (462, 'Sedative, hypnotic or anxiolytic abuse with intoxication', to_date('24/03/2018','dd/mm/yyyy'), 273, 858);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (463, 'Nondisp fx of lesser trochanter of right femur, sequela', to_date('24/03/2018','dd/mm/yyyy'), 340, 880);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (464, 'Moderate laceration of tail of pancreas, sequela', to_date('24/03/2018','dd/mm/yyyy'), 296, 297);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (465, 'Toxic effect of contact w sea anemone, undetermined, sequela', to_date('24/03/2018','dd/mm/yyyy'), 329, 33);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (466, 'Nondisp fx of lateral cuneiform of unsp ft, 7thK', to_date('24/03/2018','dd/mm/yyyy'), 305, 577);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (467, 'Finding of steroid agent in blood', to_date('24/03/2018','dd/mm/yyyy'), 316, 467);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (468, 'Toxic effect of corrosive organic compounds, assault, init', to_date('24/03/2018','dd/mm/yyyy'), 1, 137);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (469, 'Genital varices in pregnancy, first trimester', to_date('24/03/2018','dd/mm/yyyy'), 340, 550);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (470, 'Venous complications and hemorrhoids in the puerperium', to_date('24/03/2018','dd/mm/yyyy'), 304, 240);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (471, 'Disp fx of greater tuberosity of r humer, 7thP', to_date('24/03/2018','dd/mm/yyyy'), 100, 299);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (472, 'Vertical strabismus', to_date('24/03/2018','dd/mm/yyyy'), 186, 442);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (473, 'Contus/lac/hem brainstem w/o loss of consciousness', to_date('24/03/2018','dd/mm/yyyy'), 179, 423);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (474, 'Secondary infectious iridocyclitis', to_date('24/03/2018','dd/mm/yyyy'), 349, 184);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (475, 'Adverse effect of other psychotropic drugs, sequela', to_date('24/03/2018','dd/mm/yyyy'), 240, 291);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (476, 'Prsn brd/alit a 3-whl mv inj in clsn w statnry object, sqla', to_date('24/03/2018','dd/mm/yyyy'), 269, 234);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (477, 'Traum rupture of unsp ligament of l mid finger at MCP/IP jt', to_date('24/03/2018','dd/mm/yyyy'), 69, 848);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (478, 'Displ transverse fx r patella, init for opn fx type 3A/B/C', to_date('24/03/2018','dd/mm/yyyy'), 360, 314);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (479, 'Foreign body in conjunctival sac, unsp eye, subs encntr', to_date('24/03/2018','dd/mm/yyyy'), 356, 202);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (480, 'Oth fx shaft of unsp humerus, subs for fx w delay heal', to_date('24/03/2018','dd/mm/yyyy'), 374, 23);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (481, 'Displaced unsp fracture of left lesser toe(s), sequela', to_date('24/03/2018','dd/mm/yyyy'), 301, 581);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (482, 'Infect/inflm reaction due to int fix of right femur, sequela', to_date('24/03/2018','dd/mm/yyyy'), 151, 500);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (483, 'Disorders of optic nerve, not elsewhere classified', to_date('24/03/2018','dd/mm/yyyy'), 108, 891);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (484, 'Retained intrauterine contraceptive device in pregnancy', to_date('24/03/2018','dd/mm/yyyy'), 33, 736);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (485, 'Monoplg upr lmb fol oth ntrm intcrn hemor aff unsp side', to_date('24/03/2018','dd/mm/yyyy'), 17, 246);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (486, 'Toxic effect of venom of brown recluse spider, accidental', to_date('24/03/2018','dd/mm/yyyy'), 242, 845);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (487, 'Nondisp fx of dist phalanx of r thm, subs for fx w nonunion', to_date('24/03/2018','dd/mm/yyyy'), 285, 395);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (488, 'Congenital occlusion of ureteropelvic junction', to_date('24/03/2018','dd/mm/yyyy'), 333, 325);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (489, 'Mediastinal (thymic) large B-cell lymphoma, intra-abd nodes', to_date('24/03/2018','dd/mm/yyyy'), 291, 719);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (490, 'Military operations involving biological weapons', to_date('24/03/2018','dd/mm/yyyy'), 359, 48);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (491, 'Unsp inj unsp musc/fasc/tend at thi lev, right thigh, subs', to_date('24/03/2018','dd/mm/yyyy'), 297, 706);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (492, 'Disp fx of neck of unsp MC bone, subs for fx w routn heal', to_date('24/03/2018','dd/mm/yyyy'), 193, 479);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (493, 'Underdosing of hormones and synthetic substitutes, sequela', to_date('24/03/2018','dd/mm/yyyy'), 340, 172);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (494, 'Chronic angle-closure glaucoma, bilateral, severe stage', to_date('24/03/2018','dd/mm/yyyy'), 77, 358);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (495, 'Laceration of pleura, sequela', to_date('24/03/2018','dd/mm/yyyy'), 203, 64);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (496, 'Displaced Rolando''s fracture, unspecified hand', to_date('24/03/2018','dd/mm/yyyy'), 268, 870);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (497, 'Laceration of axillary artery, right side, subs encntr', to_date('24/03/2018','dd/mm/yyyy'), 76, 265);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (498, 'Sltr-haris Type III physl fx upr end unsp tibia, 7thK', to_date('24/03/2018','dd/mm/yyyy'), 23, 124);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (499, 'Other secondary chronic gout, right knee, without tophus', to_date('24/03/2018','dd/mm/yyyy'), 270, 223);
insert into REVISTA (RECURSO_ID, SINOPSIS, FECHA_PUBLICACION, EMISION, EDITORIAL_ID) values (500, 'Stenosis due to other internal prosth dev/grft, subs', to_date('24/03/2018','dd/mm/yyyy'), 125, 175);
