insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'at turpisEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'quam turpis adipiscing3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nullam porttitor56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'hac habitasse plateaEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'magna ac consequat6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tristique est789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'fringilla rhoncus maurisXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'laoreet ut rhoncus6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'suspendisse potenti56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nulla tellus inABDEFGHJ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nisl venenatis laciniaNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ametUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ultrices posuereNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vitae nislYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'congueJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ligulaLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'donecWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'luctus etBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'urna pretiumPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ultrices posuere12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'anteWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vitae mattis nibh456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nislYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ipsum primisSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'duis bibendum morbi12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nulla mollis molestieQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in hac89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'aenean auctor gravidaLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'inSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut odioBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nulla utDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'iaculis congue vivamus23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pellentesque volutpat duiWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'curae mauris23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'libero convallis89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'fusce posuereQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nulla89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'mauris morbi nonBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'diam cras pellentesque12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'justoXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'erat volutpatDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'iaculisHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'turpis integer aliquetZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'venenatis lacinia aeneanUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'volutpat inBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vel est56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'hacZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sed vel enimFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'eget eleifendPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'risusEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'atLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'adipiscing lorem3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'praesent blanditYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'convallis56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pretiumRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'quis orciYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tincidunt789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'eu magna vulputateHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'aenean auctor gravidaRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'diam namDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'non mattis pulvinar12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ultriciesSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'blanditGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ametZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tellus inPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'luctus etDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'platea dictumst maecenasJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'placerat12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'fusce posuereNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'interdum maurisFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'adipiscing molestie hendreritUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'luctus cumSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lobortis convallis tortorTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'donecQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'morbi porttitor lorem56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'consectetuer adipiscing elit12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lacusDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'congue diam id3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vitae consectetuerNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'etiam pretiumJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vel nulla egetZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'at nulla suspendisse3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'risus semper portaJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'feugiat etXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'adipiscing lorem vitaeWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sit amet6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lobortis89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lobortis ligulaEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'enim blanditSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'non sodales sed56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nec nisi vulputateJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'integer aliquetZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tortor quis turpisUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'justo inXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'convallis23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'volutpat56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'condimentum idHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pretiumQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ametJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'luctusTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'dis6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'cras pellentesqueWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nulla dapibus dolorUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'velit id pretiumABDEFGHJ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'feugiat nonPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nam3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'condimentumNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ultrices789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in ante56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'velit vivamusSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in lectus pellentesqueABDEFGHJ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tincidunt lacus12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'eros viverra eget23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'praesentRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'non interdum inQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nam duiWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vitae mattisWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'diam cras12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'et eros vestibulumEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'id nislUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'est et tempus456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'hacXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'placerat praesentRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'amet justo morbiHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'donec ut3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'mi89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pellentesque at nullaBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in imperdiet etSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'suspendisse accumsan3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'orci luctusRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vel augue vestibulumQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'integer pede justo6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'integer tincidunt3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'primisGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'aeneanYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'iaculis justo inJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'faucibus cursus456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nulla nislNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'massa volutpat convallisJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'euismod scelerisque23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'accumsan odioQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'mi in porttitor456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'volutpatHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'dictumstTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'cursus id turpisPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sodales sed12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vestibulum acYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'interdum maurisYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sedTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sedABDEFGHJ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lectus pellentesque23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'velit vivamus vel6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'turpis nec56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pede morbiGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in felis donecUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sem sedBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'aliquam nonEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nec euismod scelerisque23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'auctor gravida semLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'donec diam neque456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sem mauris laoreetNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'erat id maurisFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lobortis convallis tortorWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nec nisiTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'enimHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vel augue456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'integerFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'diam nequeDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'venenatis lacinia aeneanQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in porttitor pedeJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'habitasse platea dictumstXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'iaculis congue vivamus56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'amet turpisXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in lacusYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'rhoncus dui789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'rutrumJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'amet semFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'crasZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'montesPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'blandit3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pharetra magna ac789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'aliquet pulvinarPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut volutpatFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'volutpat eleifendXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in felis89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'accumsan odioJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nulla ac enimYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in sapien iaculisDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sed lacus3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'felisHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'libero quis789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nisl utXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'leo pellentesque ultricesLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'porta volutpat eratXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ligula sitEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nulla quisque arcuJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'habitasse platea dictumstZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'non quamXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'utUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sociis natoque penatibus56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lobortis sapienHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ipsum primisYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lectusFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'fusce89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vestibulumQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'enim blanditZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sociisLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'non maurisDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'cras in89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'venenatis nonBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut massa23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vitae quam89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'quamNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'metus aenean fermentumZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vel nisl duis3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vitae nisi23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sagittis sapien cumPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'bibendum felisHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sitWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vel accumsan tellusFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'metus aeneanJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'varius nulla facilisiTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'consectetuer adipiscing elitEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'velit necBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'duisZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'magnisRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'bibendum morbi nonLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nisi volutpatRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ligula nec semLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'disUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'idFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'donec456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'rutrumQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nunc vestibulum anteYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pulvinar lobortisHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'fusce lacus purusRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ac consequat metusPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vestibulum sit ametZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'consequat89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'volutpatLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'penatibus etSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'libero ut massaSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'donec pharetra23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'elit6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'velitGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'suscipit ligula inGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'massa id lobortisUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tinciduntXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'justoHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'luctusWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'quisque id789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'velit nec nisi23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'dictumst morbi vestibulumBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'rhoncusEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sagittisFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'justo in12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ultrices vel auguePQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'euQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'phasellus12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'volutpatQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'integer pedeHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vel nulla789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'eu miFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'maecenas tincidunt89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'porta volutpat eratQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'purusXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'id lobortis89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'hacJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'velFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sed justo456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'neque vestibulum egetSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'semper sapien a89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'consequat morbi a3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'morbi non lectusYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'donec quis orci23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sit amet eleifend456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nisi56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'aliquet maecenasHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'donec utBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'suspendisse potenti nullamHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'liberoHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sit ametNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ipsum praesent6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'quamWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'euYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'augue vestibulumLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in tempor6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'diam nam tristiquePQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vestibulumHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in imperdiet789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'hac habitasseNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lacinia eratTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'velHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'utTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'eget nuncTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'dictumstYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'justoHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'quamBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'proin leo789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pede ullamcorper3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'condimentumQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in faucibus orciJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'rutrum rutrumGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sagittis namPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pellentesque at nullaBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'penatibus et magnisUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'aliquet massa456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ligula56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'miSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'natoque penatibus etHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'id turpis integer12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'portaEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'volutpat quamJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'laciniaZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'idSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pede ullamcorperTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sapienPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vestibulum sedZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'magna at nunc6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tincidunt euGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nulla456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in sagittis duiWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tristique fusceYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sit amet3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vestibulum sedUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'amet lobortis23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vestibulumPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut erat12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'malesuada456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'euJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nullaLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'primis in12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'turpis3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'donec odio789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'morbi a ipsumTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'fusce consequat nulla3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'proin eu mi6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'turpis adipiscingWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'volutpatHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ridiculus mus6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'quam pharetra magnaNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'in est risusDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'eu felis fusceTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tortor quis turpisABDEFGHJ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nullam variusBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ultrices libero nonYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'inHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lectus suspendisse potenti89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'dui proin leoXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vestibulumJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'adipiscing elit456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'etiam faucibus cursusRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tincidunt eget56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'viverra pedeABDEFGHJ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'adipiscing lorem vitaeNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'est etABDEFGHJ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'aliquetPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'interdum maurisABDEFGHJ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'elit proin risusYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'justo nec456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nonummyYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nullaFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut eratUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'duis consequat duiHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'erosGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ante ipsum primisDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'eu6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nullamGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vestibulum sedBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'mi integerLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'et ultrices posuere789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sagittisNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'estTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pede posuere6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ametRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nonQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'purus phasellus inQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ante ipsumNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'liberoSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'felisSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'velit vivamus23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'quis liberoTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ligula inSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'mattis6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'morbi6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lacinia egetFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'mattis pulvinar nullaSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tempus semper estHJLNPQRS');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'eu789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'luctusLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tristique fuscePQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'natoque penatibus12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ac nullaEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'dolor quisGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lorem integerYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sollicitudin mi789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ipsum ac tellusBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut nulla12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pellentesque ultricesEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'phasellus in felisLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vehicula condimentum curabiturQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tortor euDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'turpis sedGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ac56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pretiumJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'leoJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'feugiat nonUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ac nullaQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'felis sedJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'luctusWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'penatibusBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'libero789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'interdum venenatis3456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tincidunt euABDEFGHJ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'hendrerit atZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nulla eget eros789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tempor turpisSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nunc rhoncusPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'volutpat eleifendWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nulla justo aliquamUWXYZ123');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ultrices posuere cubiliaNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'faucibus orci23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'neque libero23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'dolor vel23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'aliquet at feugiatYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'justo lacinia egetSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nonummy maecenas23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'auctor56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'tristiqueXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'condimentum nequeBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'luctus cum sociis6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'donec diamZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lacinia egetGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'namFGHJLNPQ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nullamZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nullamEFGHJLNP');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'posuere nonummy6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'eros viverraDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'diam vitaeWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'imperdietXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'acJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'habitasse platea dictumstRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'mauris eget massa89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lorem quisqueQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'purus89');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'integerWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'primis in faucibusPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'eget erosLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'malesuada inWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sapienSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'turpis donec posuereTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'donec6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'velWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'curabitur gravidaDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sodales sed tinciduntXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'at23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'elementum ligulaSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'vestibulum ante56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nam ultrices liberoNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nibh in quisZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'at velit euDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'luctusPQRSTUWX');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut tellus nulla23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nonBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'aliquam augueZ1234567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lorem vitaeJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ultrices vel augueTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'orciJLNPQRST');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'penatibusQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pedeWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'libero ut789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'morbi nonLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'duisNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut suscipitSTUWXYZ1');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'massaRSTUWXYZ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'proin risus6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nonummy integerBDEFGHJL');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sociis natoque penatibusNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'porta volutpat quam23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'lobortis6789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nascetur ridiculus musTUWXYZ12');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'nonummy23456789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'velYZ123456');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'pretium iaculis diam12345678');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'blandit nam nulla56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'at feugiat nonDEFGHJLN');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'morbi porttitor loremGHJLNPQR');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'quam56789');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'est phasellus sitWXYZ1234');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sedXYZ12345');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'ut odio crasLNPQRSTU');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'sed justoNPQRSTUW');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'integer ac leoABDEFGHJ');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'crasZ12dfsdfs34567');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'dictumstQRSTUWXY');
insert into PALABRA_CLAVE (PALABRA_CLAVE_ID, SUSTANTIVO_UK) values (palabra_clave_seq.nextval, 'etDEFGsdsfHJLN');
